config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#new'
resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    headers['Access-Control-Allow-Origin'] = '*'

    @message = Message.new
  end

  def create
    headers['Access-Control-Allow-Origin'] = '*'
    @message = Message.create message_params
    text = @message.message_content

    MQTT::Client.connect('mqtt://breelamp:ZbMY6$T0*2y0@192.168.0.162') do |c|
        c.publish('brookeledmatrix', text)
      end



      ####     ALTERNATIVE SERVER OPTIONS - CURRENTLY NOT IN USE
      # MQTT::Client.connect('mqtt://homeAssistant:4HyIJ02ofOYqWrGkcQ6s@m12.cloudmqtt.com', 19070) do |c|
      #     c.publish('brookeledmatrix', text)
      #   end

       # MQTT::Client.connect(
       #   host: 'a1zgckqipkzc05-ats.iot.ap-southeast-2.amazonaws.com', # Your AWS IoT host
       #   port: 8883,
       #   ssl: true,
       #   cert_file: File.absolute_path('app/assets/Server-info/LED_Matrix_Server.cert.pem'),
       #   key_file: File.absolute_path("app/assets/Server-info/LED_Matrix_Server.private.key"),
       #   ca_file: File.absolute_path("app/assets/Server-info/root-CA.crt")
       # )  do |c|
       #     c.publish('brookeledmatrix', text)
       #   end

      render json: @message
      # redirect_to messages_path

  end

  def index
    headers['Access-Control-Allow-Origin'] = '*'

    messages = Message.all
    sortedmessages = messages.sort_by { |msg| [msg.created_at] }.reverse
    @messages = sortedmessages
    render json: @messages
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def message_params
    params.require(:message).permit(:message_content)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LedMatrixApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class='container'>
      <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model:@message, local:true do |f| %>

<%= f.label :message_content, "What do you want to say?" %>
<%= f.text_field :message_content %>
<br>
<%= f.submit "Send Message to Matrix" %>
<%end %>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<h1>Previously sent Messages</h1>

<%@messages.each do |m| %>
<ul>

  <li>Message: <%= m.message_content %> </li>
  <li>Time Sent: <%= m.created_at.strftime('%d %b %Y %H:%M:%S') %> </li>

</ul>
<%end%>

<%= link_to "Send new message", new_message_path, class:"button button-primary" %>

app/views/messages/new.html.erb
<h1>Send a new Message </h1>
<br>
<%= render partial: 'form' %>

<%= link_to "See Previously Sent Message", messages_path, class:"button button-primary" %>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>